DEFAULT_IMAGE_NAME = "Frame_video.png"
DEFAULT_IMAGE_MASK_NAME = "Frame_video_mask.png"
DEFAULT_VIDEO_NAME = "Video.mp4"
DEFAULT_VIDEO_MASK_NAME = "Video_mask.mp4"

EXIT_SUCCESS = 0
# EXIT_FAILURE = 1
CONTINUE_PROCESSING = 2
