DIRECTORY_SAVING = "saving/"
DEFAULT_IMAGE_NAME = "image.jpg"
DEFAULT_VIDEO_NAME = "Video.mp4"

DEFAULT_FRAME_WINDOW_NAME = "frame"
DEFAULT_MASK_WINDOW_NAME = "foreground mask"

EXIT_SUCCESS = 0
# EXIT_FAILURE = 1
CONTINUE_PROCESSING = 2
